# ===================================
#  Configures the partial list widget
# ===================================

titleProperty: name
descriptionProperty: short_desc
noRecordsMessage: 'cms::lang.partial.no_list_records'
deleteConfirmation: 'cms::lang.partial.delete_confirm_multiple'
itemType: menu
