# ===================================
#  Form Behavior Config
# ===================================

form: $/flynsarmy/menu/models/settings/fields.yaml
modelClass: Flynsarmy\Menu\Models\Settings
defaultRedirect: flynsarmy/menu/settings